#!/usr/bin/env python3
"""Audit Lean's actual axiom dependencies, including the unfinished main theorem.

Run after building Solution. The independent Challenge is deliberately excluded:
its statement hole is permitted, whereas the proved theorem must be axiom-clean.
This is a development gate, not a substitute for sandboxed Comparator replay.
"""

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MAIN_THEOREM = "FalconerThetaGauge.theorem_one_one"
STANDARD_AXIOMS = {"propext", "Classical.choice", "Quot.sound"}
FOUNDATIONS = (
    "FalconerThetaGauge.realGauge",
    "FalconerThetaGauge.thetaGauge",
    "FalconerThetaGauge.gaugeMeasure",
    "FalconerThetaGauge.distanceSet",
    "FalconerThetaGauge.thetaGauge_zero",
    "FalconerThetaGauge.thetaGauge_pos",
    "FalconerThetaGauge.thetaGauge_le",
    "FalconerThetaGauge.measurableSet_distanceSet",
    "FalconerThetaGauge.gaugeMeasure_le_hausdorffMeasure_one",
    "FalconerThetaGauge.eventually_log_le_mul_rpow",
    "FalconerThetaGauge.summable_exp_neg_mul_nat_rpow",
    "FalconerThetaGauge.summable_filter_power",
    "FalconerThetaGauge.gain_eq_mul_rpow",
    "FalconerThetaGauge.realGauge_double_le",
    "FalconerThetaGauge.gaugeContent_pos_of_gaugeMeasure_pos",
    "FalconerThetaGauge.GaugeFrostman.exists_finite_gauge_weights",
    "FalconerThetaGauge.summable_l2_of_dyadicFrequencyShell_support",
    "FalconerThetaGauge.reconstruction_of_summable_errors_and_square_bound",
    "FalconerThetaGauge.exists_gauge_frostman_probabilityMeasure",
    "FalconerThetaGauge.exists_probabilityMeasure_finite_logCriticalEnergy",
    "FalconerThetaGauge.dyadicGaussianKernel_le_log",
    "FalconerThetaGauge.summable_rounded_filter_error",
    "FalconerThetaGauge.eventually_log_le_blockParameter_cube_mul_scale",
    "FalconerThetaGauge.absolutelyContinuous_of_l1_fourier_l2_schwartz_pairing",
    "FalconerThetaGauge.tendsto_integral_reconstructionLowpass_schwartz",
    "FalconerThetaGauge.exists_parameter_threshold",
    "FalconerThetaGauge.summable_reconstruction",
    "FalconerThetaGauge.absolutelyContinuous_of_summable_dyadic_reconstruction",
    "FalconerThetaGauge.exists_prepared_probabilityMeasures_finite_logCriticalEnergy",
    "FalconerThetaGauge.volume_distanceSet_affineMap_image_pos_iff",
    "FalconerThetaGauge.logarithmicFourierEnergy_le",
    "FalconerThetaGauge.logarithmicFourierEnergy_ne_top",
    "FalconerThetaGauge.volume_distanceSet_pos_of_crossDistanceMeasure_absolutelyContinuous",
    "FalconerThetaGauge.summable_filterMassError",
    "FalconerThetaGauge.regularDyadicPartMeasure_isRegularThrough",
    "FalconerThetaGauge.regular_decomposition",
    "FalconerThetaGauge.ae_orthogonalProjectionDensity_L2",
    "FalconerThetaGauge.compProd_orthogonalProjectionKernel_eq_withDensity",
    "FalconerThetaGauge.integral_canonical_density_level_le_charFun_tail",
    "FalconerThetaGauge.logarithmic_amplitude_layer_le",
    "FalconerThetaGauge.lintegral_orliczQuadratic_canonical_le",
    "FalconerThetaGauge.map_inverse_distance_radialProjection_withDensity_eq",
    "FalconerThetaGauge.continuousOn_radialProjection_of_separated",
    "FalconerThetaGauge.absolutelyContinuous_of_tendsto_of_uniform_orlicz",
    "FalconerThetaGauge.lintegral_orliczQuadratic_orthogonalProjectionDensity_le",
    "FalconerThetaGauge.lintegral_circle_lineLogFourierEnergy_eq",
    "FalconerThetaGauge.measure_rnDeriv_tail_le",
    "FalconerThetaGauge.weak_limit_orlicz_density",
    "FalconerThetaGauge.regularMeasureExcess_normalizedRestrict_properties",
    "FalconerThetaGauge.occupiedCellDescendants_count_le",
    "FalconerThetaGauge.regularDyadicPartMeasure_excess_properties",
    "FalconerThetaGauge.regularDyadicPart_entry_properties",
    "FalconerThetaGauge.profileSplitPoint_right_budget_gain",
    "FalconerThetaGauge.profileSplitPoint_left_budget_gain",
    "FalconerThetaGauge.profileScheduledTests_card_le_scale_sq",
    "FalconerThetaGauge.lintegral_orliczPhi_angularLineDensity_pinProjection_le",
    "FalconerThetaGauge.ae_radialProjection_orlicz_density_of_approximating_sources",
    "FalconerThetaGauge.ae_radialProjection_orlicz_density_prepared",
    "FalconerThetaGauge.exists_prepared_probabilityMeasures_uniform_radial_orlicz",
    "FalconerThetaGauge.withDensity_filter_bad_directions_of_budget",
    "FalconerThetaGauge.norm_iteratedDeriv_reciprocal_le",
    "FalconerThetaGauge.nonstationary_phase",
    "FalconerThetaGauge.nonstationary_phase_periodic",
    "FalconerThetaGauge.linear_phase",
    "FalconerThetaGauge.integral_norm_iteratedDeriv_explicitBump_le",
    "FalconerThetaGauge.norm_iteratedDeriv_circlePassingMask_comp_angle_le",
    "FalconerThetaGauge.measurable_partitionCirclePassingSymbol",
    "FalconerThetaGauge.circleArcLength_directionalTestFailure_le",
    "FalconerThetaGauge.measurable_tubeCount",
    "FalconerThetaGauge.circleArcLength_scheduled_failure_le",
    "FalconerThetaGauge.scheduledTestFailureSet_short",
    "FalconerThetaGauge.norm_iteratedDeriv_scheduledTestSymbol_comp_angle_le",
    "FalconerThetaGauge.scheduledDirectionalFilter",
    "FalconerThetaGauge.weightedCrossDistanceMeasure_univ_bounds",
    "FalconerThetaGauge.volume_distanceSet_pos_of_weightedCrossDistanceMeasure_absolutelyContinuous",
    "FalconerThetaGauge.finiteTestFilteredDistanceMeasure_mass_loss",
    "FalconerThetaGauge.finiteTestFilteredDistanceMeasure_regular_mass_loss",
    "FalconerThetaGauge.finiteTestFilteredDistanceSequence_summable_removed_mass",
    "FalconerThetaGauge.ProfileMoveChain.totalCost_le_excess_final_point",
    "FalconerThetaGauge.ProfileMoveChain.multiplierProduct_le_totalCost_add_two_block",
    "FalconerThetaGauge.profileChildStates_wellFounded",
    "FalconerThetaGauge.profilePieceTests_card_le_scale_sq_add_one",
    "FalconerThetaGauge.profileInductionNodes_card_le_block_power",
    "FalconerThetaGauge.profileInductionVisits_card_le_block_power",
    "FalconerThetaGauge.parameter_shell_numeric_bound",
    "FalconerThetaGauge.parameter_energy_closing_bound",
    "FalconerThetaGauge.scalarCollisionMass_shift_le_four",
    "FalconerThetaGauge.scalarCollisionMass_dilate_le",
    "FalconerThetaGauge.lintegral_scalarBinningKernel_le_ten",
    "FalconerThetaGauge.fourier_quadraticGaussian",
    "FalconerThetaGauge.integral_quadraticGaussian_mul_schwartz_of_re_zero",
    "FalconerThetaGauge.quadratic_phase_fourier_identity",
    "FalconerThetaGauge.quadraticPhasePrefactor_eq",
    "FalconerThetaGauge.norm_imaginaryExponential_sub_sum_le",
    "FalconerThetaGauge.integral_fourierInv_derivative_power_le",
    "FalconerThetaGauge.quadratic_phase_expansion",
    "FalconerThetaGauge.quadratic_phase_compact_negative",
    "FalconerThetaGauge.contDiff_stationaryMorseAmplitude",
    "FalconerThetaGauge.localizedCircleIntegral_eq_quadratic",
    "FalconerThetaGauge.localizedCircleIntegral_expansion",
    "FalconerThetaGauge.iteratedDeriv_stationaryMorse_weighted_deriv",
    "FalconerThetaGauge.stationaryPhaseOperator_eq_scaled_derivative",
    "FalconerThetaGauge.stationaryPhaseConjugateOperator_eq_scaled_derivative",
    "FalconerThetaGauge.closedArcNeighborhood_scheduledPassing_subset",
    "FalconerThetaGauge.scheduled_level_passing_neighborhood",
    "FalconerThetaGauge.real_projectionAnchor_closedBall_le_excess",
    "FalconerThetaGauge.occupiedCellCentersInBall_count_le_excess",
    "FalconerThetaGauge.tubeAverage_le_height_of_parameterFacts",
    "FalconerThetaGauge.projectionAverage_le_height_of_parameterFacts",
    "FalconerThetaGauge.prepared_carriers_common_direction_arc",
    "FalconerThetaGauge.regularDirectionalFilter",
    "FalconerThetaGauge.regularDirectionalFilter_carrier",
    "FalconerThetaGauge.scheduledFilteredDistanceMeasure_mass_loss",
    "FalconerThetaGauge.contDiff_regularDirectionalFilter_symbol_comp_angle",
    "FalconerThetaGauge.regularDirectionalFilter_symbol_derivative_budget_sup",
    "FalconerThetaGauge.scalarCollisionMass_le_two_mul_fourierEnergy",
    "FalconerThetaGauge.scalarFourierWindowEnergy_le_160_collision",
    "FalconerThetaGauge.norm_iteratedDeriv_circularStationaryCutoff_le",
    "FalconerThetaGauge.iteratedDeriv_real_of_complex",
    "FalconerThetaGauge.norm_iteratedDeriv_stationaryMorseJacobian_le",
    "FalconerThetaGauge.sum_stationaryPartitionWeight_le",
    "FalconerThetaGauge.sum_stationaryPartitionCycleWeight_eq",
    "FalconerThetaGauge.norm_iteratedDeriv_comp_le_gevrey",
    "FalconerThetaGauge.norm_iteratedDeriv_stationaryMorseAmplitude_le",
    "FalconerThetaGauge.localizedCircleIntegral_operator_expansion",
    "FalconerThetaGauge.stationaryCompositionWeightedNorm_le",
    "FalconerThetaGauge.stationaryDerivativeWeightedNorm_le",
    "FalconerThetaGauge.stationaryPhaseWeightedNorm_le",
    "FalconerThetaGauge.stationaryPhasePolynomial_inverse_convolution",
    "FalconerThetaGauge.stationaryPhase_inverse_operator_cancellation",
    "FalconerThetaGauge.stationaryPhase_conjugate_inverse_operator_cancellation",
    "FalconerThetaGauge.maskedFourierEnergy_le",
    "FalconerThetaGauge.maskedFourierEnergy_cells_le_excess",
    "FalconerThetaGauge.maskedFourierEnergy_scheduled_drop_reached",
    "FalconerThetaGauge.contDiff_circularStationaryPeriodicCutoff",
    "FalconerThetaGauge.tsupport_circularStationaryAwayCutoff_subset",
    "FalconerThetaGauge.norm_circularStationaryAway_integral_le",
    "FalconerThetaGauge.circularStationary_integral_eq_localized_add_away",
    "FalconerThetaGauge.preparedArcCutoff_pairDirection_eq_one",
    "FalconerThetaGauge.iteratedDeriv_preparedArcCutoff_eq_zero_on_opposite",
    "FalconerThetaGauge.norm_iteratedDeriv_preparedArcCutoff_le",
    "FalconerThetaGauge.polynomialWeightedNorm_mul_le",
    "FalconerThetaGauge.stationaryPhaseInversePolynomial_weightedNorm_le",
    "FalconerThetaGauge.polynomialDifferentialAction_isDerivativeRegular",
    "FalconerThetaGauge.stationaryPhaseConjugateInverseOperator_isDerivativeRegular_budget",
    "FalconerThetaGauge.stationaryPhaseTruncatedConvolution_weightedNorm_le",
    "FalconerThetaGauge.stationaryPhaseFiniteProduct_eq_add_tail",
    "FalconerThetaGauge.norm_stationaryPhaseFiniteTail_le_geometric",
    "FalconerThetaGauge.factorial_double_add_two_sq_le",
    "FalconerThetaGauge.localizedCircleIntegral_operator_expansion_explicit",
    "FalconerThetaGauge.localizedCircleIntegral_conjugate_operator_expansion_explicit",
    "FalconerThetaGauge.circularIntegral_operator_expansion_source_budget",
    "FalconerThetaGauge.circular_stationary_phase",
    "FalconerThetaGauge.maskedDistanceEnergy_le",
    "FalconerThetaGauge.maskedDistanceEnergy_cells_le_excess",
    "FalconerThetaGauge.scheduledDistanceEnergy_mono_level",
    "FalconerThetaGauge.angularScalarFourier_passingWeightedDistanceMeasure_eq_iterated",
    "FalconerThetaGauge.normalizedDistanceCollisionEnergy_le_320_low_high_dyadic",
    "FalconerThetaGauge.scheduledWidthMaskProduct_ne_zero_implies_next_passing",
    "FalconerThetaGauge.levelMaskedDistanceMeasure_le_nextPassing",
    "FalconerThetaGauge.scheduledDistanceEnergy_cells_low_high",
    "FalconerThetaGauge.regularMeasurePieceTests_ordered",
    "FalconerThetaGauge.ScheduledSymbolData.measurable_symbol",
    "FalconerThetaGauge.ScheduledSymbolData.abs_symbol_le_one",
    "FalconerThetaGauge.ScheduledSymbolData.ne_zero_implies_next_passing",
    "FalconerThetaGauge.ScheduledSymbolData.iteratedDeriv_symbol_eq",
    "FalconerThetaGauge.ScheduledSymbolData.sum_abs_branchCoefficients_le",
    "FalconerThetaGauge.isDerivativeRegular_of_mem_scheduledSymbolClass",
    "FalconerThetaGauge.scheduledSymbolScale_le_parameterBound",
    "FalconerThetaGauge.regularDirectionalFilter_symbol_isDerivativeRegular_eight",
    "FalconerThetaGauge.maskedFourierEnergy_builtSymbol_drop_reached",
    "FalconerThetaGauge.maskedFourierEnergy_le_scheduledFourierEnergySup",
    "FalconerThetaGauge.scheduledFourierEnergySup_drop_reached",
    "FalconerThetaGauge.scheduledFourierEnergySup_cells_le_excess",
    "FalconerThetaGauge.regularMeasureStateEnergy_discrepancy_le_excess",
    "FalconerThetaGauge.regularMeasureStateEnergy_fourier_le_excess",
    "FalconerThetaGauge.hasSumUniformlyOn_spatialInversePowerSequenceTerm",
    "FalconerThetaGauge.tsum_spatialInversePowerSequenceCoefficient_abs_le",
    "FalconerThetaGauge.separated_inverse_powers",
    "FalconerThetaGauge.preparedAngularCutoff_isDerivativeRegular",
    "FalconerThetaGauge.stationaryPhaseConjugateOperator_preparedAngularAmplitude_eq_zero",
    "FalconerThetaGauge.circular_stationary_phase_prepared_arc",
    "FalconerThetaGauge.preparedInverseCircleSeries_sub_eq",
    "FalconerThetaGauge.preparedInverseCircleSeries_approximation",
    "FalconerThetaGauge.preparedInverseCircleSeries_normalized_approximation",
    "FalconerThetaGauge.stationary_decay_ratio_pow_le_of_parameters",
    "FalconerThetaGauge.prepared_stationary_remainder_le_terminal",
    "FalconerThetaGauge.preparedInverseCircleSeries_source_error",
    "FalconerThetaGauge.builtSymbolAngularAmplitude_isDerivativeRegular",
    "FalconerThetaGauge.builtPairSymbolScale_le_frequency",
    "FalconerThetaGauge.builtSymbolPair_pointwise_mattila_inversion",
    "FalconerThetaGauge.norm_maskedFourierBilinearAmplitude_sq_le",
    "FalconerThetaGauge.integral_maskedFourierBilinearAmplitude_sq_le",
    "FalconerThetaGauge.norm_sum_mul_add_sq_le_weighted",
    "FalconerThetaGauge.integral_sum_maskedFourierBilinearAmplitude_sq_le",
    "FalconerThetaGauge.norm_tsum_mul_add_sq_le_weighted",
    "FalconerThetaGauge.integral_norm_tsum_mul_sq_le_weighted",
    "FalconerThetaGauge.integral_tsum_maskedFourierBilinearAmplitude_sq_le",
    "FalconerThetaGauge.sum_smoothIndicator_partition",
    "FalconerThetaGauge.sum_equalAngularPartition",
    "FalconerThetaGauge.angularPartitionCount_le",
    "FalconerThetaGauge.equalAngularCellWidth_lower",
    "FalconerThetaGauge.sum_equalArcCutoff",
    "FalconerThetaGauge.equalArcCutoff_isDerivativeRegular",
    "FalconerThetaGauge.finite_graph_schur",
    "FalconerThetaGauge.norm_sum_sq_le_graph_schur",
    "FalconerThetaGauge.circleQuarterTurn_unitCircleOfAngle",
    "FalconerThetaGauge.norm_sub_dyadicCellCenter_le",
    "FalconerThetaGauge.orthogonality_point_center_perp_error",
    "FalconerThetaGauge.orthogonality_unlinked_phase_separation",
    "FalconerThetaGauge.scheduledFourierEnergySup_remaining_le_refined_state",
    "FalconerThetaGauge.regularMeasureStateEnergy_short_le_parameterBudget",
    "FalconerThetaGauge.actual_weighted_short_leaf_le_budget",
    "FalconerThetaGauge.preparedInverseCircleKernelIntegral_eq_angular",
    "FalconerThetaGauge.preparedInverseCircleKernelSeries_eq_angular",
    "FalconerThetaGauge.builtSymbolPair_circle_mattila_inversion",
    # Actual new separation, linearization, and orthogonality dependencies.
    "FalconerThetaGauge.normLinearizationError_eq",
    "FalconerThetaGauge.normLinearizationError_nonneg",
    "FalconerThetaGauge.normLinearizationError_le",
    "FalconerThetaGauge.pairDistance_linearization",
    "FalconerThetaGauge.pairDistanceLinearizationError_nonneg",
    "FalconerThetaGauge.pairDistanceLinearizationError_le",
    "FalconerThetaGauge.scalarCollisionMass_cross_le_three_bins",
    "FalconerThetaGauge.scalarCollisionMass_cross_le_three",
    "FalconerThetaGauge.scalarBinSquareMass_finsetSum_le",
    "FalconerThetaGauge.abs_sub_dyadicCellCenter_coord_le_half",
    "FalconerThetaGauge.pair_cell_displacement_sq_le",
    "FalconerThetaGauge.dyadicRadius_square_div_radius",
    "FalconerThetaGauge.pairDistanceLinearizationError_cells_le",
    "FalconerThetaGauge.pairDistance_collision_projection_le",
    "FalconerThetaGauge.distance_collision_projection_collision_cells",
    "FalconerThetaGauge.norm_normalized_sub_le",
    "FalconerThetaGauge.norm_pairDirection_sub_le",
    "FalconerThetaGauge.norm_pair_displacement_sub_lt",
    "FalconerThetaGauge.norm_pairDirection_sub_cells_le",
    "FalconerThetaGauge.maskedDistanceEnergy_le_of_raw_collision",
    "FalconerThetaGauge.scheduledDistanceEnergy_le_linearization_constant",
    "FalconerThetaGauge.linearization_constant_le_height",
    "FalconerThetaGauge.scheduledDistanceEnergy_le_linearization",
    "FalconerThetaGauge.scheduledDistanceEnergy_level_le_linearization",
    "FalconerThetaGauge.scalarCollisionMass_eq_zero_of_carriers",
    "FalconerThetaGauge.scalarCollisionMass_self_eq_mass_sq_of_diameter",
    "FalconerThetaGauge.scalarCollisionMass_groups_eq_zero",
    "FalconerThetaGauge.scalarCollisionMass_group_self_eq_mass_sq",
    "FalconerThetaGauge.scalar_group_neighbors_card_le",
    "FalconerThetaGauge.abs_dist_sub_cell_centers_le",
    "FalconerThetaGauge.pair_distance_mem_group_interval",
    "FalconerThetaGauge.linearization_group_interval_diameter",
    "FalconerThetaGauge.linearization_group_collision_neighbors",
    "FalconerThetaGauge.scalarCollisionMass_sum",
    "FalconerThetaGauge.scalarBinSquareMass_sum_le",
    "FalconerThetaGauge.scalarBinSquareMass_sum_le_of_component_collision",
    "FalconerThetaGauge.scalarCollisionMass_cross_le_of_bin_bounds",
    "FalconerThetaGauge.scalarCollisionMass_sum_le_graph",
    "FalconerThetaGauge.linearization_group_neighbor_degree_le_nine",
    "FalconerThetaGauge.scalarCollisionMass_sum_groups_le",
    "FalconerThetaGauge.sum_linearization_group_mass_sq_le_collision",
    "FalconerThetaGauge.sum_linearization_group_mass_sq_le_nine_collision",
    "FalconerThetaGauge.measurePreserving_fourPointRegroup",
    "FalconerThetaGauge.projectionShiftedPairMass_eq_scalarCollision",
    "FalconerThetaGauge.projectionShiftedPairMass_le_four",
    "FalconerThetaGauge.scalarCollisionMass_crossDistance_eq_regrouped",
    "FalconerThetaGauge.projectionFourPointCollisionMass_le_four",
    "FalconerThetaGauge.scalarCollisionMass_crossDistance_cells_le_projection",
    "FalconerThetaGauge.measurableSet_fineCellPairCarrier",
    "FalconerThetaGauge.dyadicCellPairs_pairwiseDisjoint",
    "FalconerThetaGauge.map_distance_restrict_fineCellPairCarrier",
    "FalconerThetaGauge.dyadicCube_subset_of_mem_occupiedCellDescendants",
    "FalconerThetaGauge.retainedFineCellPairs_subset_coarse",
    "FalconerThetaGauge.passingUnweightedDistanceMeasure_retained_eq_sum",
    "FalconerThetaGauge.ae_passing_pair_mem_retained_carrier",
    "FalconerThetaGauge.passingUnweightedDistanceMeasure_le_retained",
    "FalconerThetaGauge.scalarCollisionMass_weighted_toReal_bounds",
    "FalconerThetaGauge.unweightedDistanceCollisionEnergy_nonneg",
    "FalconerThetaGauge.maskedDistanceEnergy_unweighted_bounds",
    "FalconerThetaGauge.maskedDistanceEnergy_cells_unweighted_bounds",
    "FalconerThetaGauge.crossDistanceMeasure_cells_univ",
    "FalconerThetaGauge.retained_cell_collision_le_height",
    "FalconerThetaGauge.passingUnweightedCollision_toReal_le_shortened",
    "FalconerThetaGauge.scalarCollisionMass_sum_toReal_le_group_bound",
    "FalconerThetaGauge.sum_finiteScalarGroupMeasures",
    "FalconerThetaGauge.ae_crossDistanceMeasure_cell_group",
    "FalconerThetaGauge.ae_finiteScalarGroupMeasure_interval",
    "FalconerThetaGauge.linearizationCellCoefficient_pos",
    "FalconerThetaGauge.scalarCollisionMass_crossDistance_cells_le_height",
    "FalconerThetaGauge.real_scalarCollisionMass_crossDistance_cells_le_height",
    "FalconerThetaGauge.smul_projectionAnchorMeasure_eq_restrict",
    "FalconerThetaGauge.projectionShiftedPairMass_restrict_eq_count",
    "FalconerThetaGauge.scalarCollisionMass_crossDistance_cells_le_four_count",
    "FalconerThetaGauge.retainedFineCellPairCarrier_subset_shortened_passing",
    "FalconerThetaGauge.sum_crossDistanceMeasure_retained_le_shortened",
    "FalconerThetaGauge.passingWeightedDistanceMeasure_eq_restricted_product",
    "FalconerThetaGauge.passingWeightedDistanceMeasure_le_smul_unweighted",
    "FalconerThetaGauge.smul_unweighted_le_passingWeightedDistanceMeasure",
    "FalconerThetaGauge.ofReal_inv_sqrt_le_crossDistanceWeight",
    "FalconerThetaGauge.scalarCollisionMass_smul",
    "FalconerThetaGauge.scalarCollisionMass_weighted_le",
    "FalconerThetaGauge.scalarCollisionMass_unweighted_le",
    "FalconerThetaGauge.linearization_direction_motion_le_test_scale",
    "FalconerThetaGauge.retained_pair_scheduled_passing",
    "FalconerThetaGauge.retained_center_projection_passing",
    "FalconerThetaGauge.retained_center_projection_count_le_height",
    "FalconerThetaGauge.retained_pair_passing_pin",
    "FalconerThetaGauge.scheduledPassingPinSet_antipodal",
    "FalconerThetaGauge.scheduledPassingPinSet_pairDirection_swap",
    "FalconerThetaGauge.retained_cell_pair_subset_shortened_passing",
    "FalconerThetaGauge.norm_iteratedDeriv_equalArcCutoff_le_of_order",
    "FalconerThetaGauge.equalArcCutoff_isDerivativeRegular_of_order",
    "FalconerThetaGauge.abs_angle_sub_le_of_small_chord",
    "FalconerThetaGauge.equalArcCutoff_support_chord_le",
    "FalconerThetaGauge.equalArcCutoff_support_period_subset",
    "FalconerThetaGauge.equalArcCutoff_support_period_mass_le",
    "FalconerThetaGauge.finite_fiber_count_le_mul",
    "FalconerThetaGauge.integrable_real_inner_of_memLp_two",
    "FalconerThetaGauge.integral_norm_sum_sq_le_graph_schur",
    "FalconerThetaGauge.separated_inversePower_bilinear_hasSum",
    "FalconerThetaGauge.separation_left_symbol_mem_class",
    "FalconerThetaGauge.separation_right_symbol_mem_class",
    "FalconerThetaGauge.one_le_scheduledPairCommonScale",
    "FalconerThetaGauge.scheduledSymbolScale_left_le_common",
    "FalconerThetaGauge.scheduledSymbolScale_right_le_common",
    "FalconerThetaGauge.scheduledPairCommonScale_le_frequency",
    "FalconerThetaGauge.mattila_coefficient_polynomial_le_sourceBudget",
    "FalconerThetaGauge.mattila_coefficient_base_le",
    "FalconerThetaGauge.finite_geometric_sum_le_one_point_one",
    "FalconerThetaGauge.source_coefficient_decay_sum_le",
    "FalconerThetaGauge.contDiff_iteratedDeriv_real_infty",
    "FalconerThetaGauge.iteratedDeriv_complex_ofReal",
    "FalconerThetaGauge.ScheduledSymbolData.iteratedDeriv_complex_symbol_eq",
    "FalconerThetaGauge.scheduledSymbolPair_iteratedDeriv_eq",
    "FalconerThetaGauge.measurable_scheduledPairFrequencyCoefficient",
    "FalconerThetaGauge.norm_scheduledPairFrequencyCoefficient_le",
    "FalconerThetaGauge.summable_scheduledPairFrequencyMajorant",
    "FalconerThetaGauge.polynomialWeightedNorm_mono_scale",
    "FalconerThetaGauge.tsum_scheduledPairFrequencyMajorant_inverse_le",
    "FalconerThetaGauge.tsum_scheduledPairFrequencyMajorant_inverse_dyadic_le",
    "FalconerThetaGauge.integral_scheduledPairOperator_inverse_circle_eq",
    "FalconerThetaGauge.integrable_spatial_preparedInverseCircleKernel",
    "FalconerThetaGauge.preparedInverseCircleKernelSeries_spatial_eq",
    "FalconerThetaGauge.hasSum_finite_complex_sigma",
    "FalconerThetaGauge.measurable_scheduledPairFullFrequencyCoefficient",
    "FalconerThetaGauge.preparedInverseCircleKernelSeries_spatial_hasSum",
    "FalconerThetaGauge.summable_scheduledPairFullFrequencyMajorant",
    "FalconerThetaGauge.norm_scheduledPairFullFrequencyCoefficient_le",
    "FalconerThetaGauge.scheduledPairFullLeftSymbol_mem_class",
    "FalconerThetaGauge.scheduledPairFullRightSymbol_mem_class",
    "FalconerThetaGauge.tsum_scheduledPairFullFrequencyMajorant_le",
    "FalconerThetaGauge.integrable_inversePowerCircleKernel",
    "FalconerThetaGauge.integral_inversePowerCircleKernel_eq",
    "FalconerThetaGauge.separated_inversePower_circleIntegral_hasSum",
    "FalconerThetaGauge.scheduledPairOperatorPairing_inverse_eq",
    "FalconerThetaGauge.preparedInverseCircle_spatial_hasSum",
    "FalconerThetaGauge.spatialFourierPhase_factorization",
    "FalconerThetaGauge.maskedFourierPairKernel_factorization",
    "FalconerThetaGauge.integral_maskedFourierPairKernel",
    "FalconerThetaGauge.measurable_maskedFourierPairKernel",
    "FalconerThetaGauge.norm_maskedFourierPairKernel",
    "FalconerThetaGauge.integral_spatial_circle_maskedFourierPairKernel",
    "FalconerThetaGauge.sum_abs_scheduledSymbolPair_derivative_coefficients_le",
    "FalconerThetaGauge.polynomialDifferentialAction_scheduledSymbolPair_eq",
    "FalconerThetaGauge.sum_norm_scheduledSymbolPair_operator_coefficients_le",
    "FalconerThetaGauge.sum_scheduledPairOperatorBranch",
    "FalconerThetaGauge.scheduledPairOperatorLeftData_order_le",
    "FalconerThetaGauge.scheduledPairOperatorRightData_order_le",
    "FalconerThetaGauge.polynomialDifferentialAction_scheduledPairOperator_eq",
    "FalconerThetaGauge.sum_norm_scheduledPairOperatorBranchCoefficient_le",
    "FalconerThetaGauge.scheduledPairOperatorCircleKernel_eq",
    "FalconerThetaGauge.integrable_scheduledPairOperatorCircleKernel",
    "FalconerThetaGauge.scheduledPairOperatorPairing_eq_finite",
    "FalconerThetaGauge.hasSum_finite_complex_prod",
    "FalconerThetaGauge.scheduledPairOperatorPairing_hasSum",
    "FalconerThetaGauge.scheduledPairSeparatedLeftSymbol_mem_class",
    "FalconerThetaGauge.scheduledPairSeparatedRightSymbol_mem_class",
    "FalconerThetaGauge.summable_finite_norm_mul_abs",
    "FalconerThetaGauge.summable_norm_scheduledPairSeparatedCoefficient",
    "FalconerThetaGauge.tsum_norm_scheduledPairSeparatedCoefficient_eq",
    "FalconerThetaGauge.tsum_norm_scheduledPairSeparatedCoefficient_le",
    "FalconerThetaGauge.tsum_scheduledPairFullFrequencyMajorant_le_of_parameters",
    "FalconerThetaGauge.scheduledPairFullLeftMaskSymbol_mem_class",
    "FalconerThetaGauge.scheduledPairFullRightMaskSymbol_mem_class",
    "FalconerThetaGauge.measurable_carrierPolynomialWeight",
    "FalconerThetaGauge.abs_carrierPolynomialWeight_le_one",
    "FalconerThetaGauge.measurable_carrierPolynomialSymbol",
    "FalconerThetaGauge.abs_carrierPolynomialSymbol_le_one",
    "FalconerThetaGauge.carrierPolynomialSymbol_eq_on_carrier",
    "FalconerThetaGauge.ScheduledSymbolData.withCarrierPolynomial_order",
    "FalconerThetaGauge.ScheduledSymbolData.withCarrierPolynomial_symbol",
    "FalconerThetaGauge.carrierPolynomialSymbol_mem_scheduledSymbolClass",
    "FalconerThetaGauge.hasSum_separatedInversePowerKernelTerm",
    "FalconerThetaGauge.measurable_inversePowerCircleKernel",
    "FalconerThetaGauge.norm_separatedInversePowerKernelTerm_le",
    "FalconerThetaGauge.hasSum_integral_separatedInversePowerKernelTerm",
    "FalconerThetaGauge.maskedFourierAmplitude_biUnion",
    "FalconerThetaGauge.maskedFourierAmplitude_eq_zero_of_real_mass_zero",
    "FalconerThetaGauge.maskedFourierAmplitude_cellUnion",
    "FalconerThetaGauge.maskedFourierAmplitude_occupiedCellDescendants",
    "FalconerThetaGauge.source_pair_distance_lower_cells",
    "FalconerThetaGauge.source_pair_distance_lower_root",
    "FalconerThetaGauge.source_frequency_distance_lower",
    "FalconerThetaGauge.source_pair_distance_terminal_lower",
    "FalconerThetaGauge.source_spatial_inverse_coefficient_root",
    "FalconerThetaGauge.source_spatial_inverse_coefficient_cells",
    "FalconerThetaGauge.dyadicCube_subset_closedBall_twice_radius",
    "FalconerThetaGauge.source_spatial_separated_balls_cells",
    "FalconerThetaGauge.source_spatial_separated_balls_root",
    "FalconerThetaGauge.pairDirection_mem_arc_of_relative_displacement",
    "FalconerThetaGauge.dist_dyadicCellCenter_le_two_radius",
    "FalconerThetaGauge.pairDirection_mem_arc_of_separatedDyadicCells",
    "FalconerThetaGauge.norm_intervalIntegral_le_support_mass",
    "FalconerThetaGauge.norm_intervalIntegral_oscillatoryPhase_mul_factorial_support_le",
    "FalconerThetaGauge.nonstationary_phase_periodic_support",
    "FalconerThetaGauge.orthogonalityArcScale_eq_rpow",
    "FalconerThetaGauge.orthogonalityArcScale_inv_le_frequency",
    "FalconerThetaGauge.scheduled_mask_orthogonality_factor_le",
    "FalconerThetaGauge.orthogonalityAngularAmplitude_isDerivativeRegular",
    "FalconerThetaGauge.orthogonalityAngularScale_le_frequency",
    "FalconerThetaGauge.orthogonality_angular_polynomial_le_sourceBudget",
    "FalconerThetaGauge.orthogonality_angular_decay_ratio_le",
    "FalconerThetaGauge.orthogonality_angular_decay_pow_le",
    "FalconerThetaGauge.orthogonality_angular_decay_pow_le_of_parameters",
    "FalconerThetaGauge.orthogonalityAngularPhaseRatio_le_frequency",
    "FalconerThetaGauge.orthogonalityAngularPhaseLambda_le_frequency",
    "FalconerThetaGauge.orthogonality_angular_nonstationary",
    "FalconerThetaGauge.orthogonalityAngularPhase_zero",
    "FalconerThetaGauge.orthogonalityAngularPhase_eq_circular",
    "FalconerThetaGauge.contDiff_orthogonalityAngularPhase",
    "FalconerThetaGauge.orthogonalityAngularPhase_periodic",
    "FalconerThetaGauge.deriv_orthogonalityAngularPhase",
    "FalconerThetaGauge.norm_iteratedDeriv_orthogonalityAngularPhase_le",
    "FalconerThetaGauge.orthogonalityAngularAmplitude_support_subset",
    "FalconerThetaGauge.orthogonalityAngularAmplitude_support_mass_le",
    "FalconerThetaGauge.orthogonalityAngularAmplitude_support_perp_low",
    "FalconerThetaGauge.orthogonality_angular_source_decay",
    "FalconerThetaGauge.activeLinkedFirstColumns_fiber_count_le",
    "FalconerThetaGauge.activeLinkedFirstColumns_count_le",
    "FalconerThetaGauge.norm_sq_eq_inner_quarter_sq_add",
    "FalconerThetaGauge.norm_le_three_of_two_coordinates",
    "FalconerThetaGauge.mem_dyadicCenterBallIndexBox",
    "FalconerThetaGauge.card_dyadicCenterBallIndexBox",
    "FalconerThetaGauge.dyadicCenterBallIndexBox_card_le",
    "FalconerThetaGauge.finite_dyadic_center_count_le",
    "FalconerThetaGauge.finite_dyadic_link_count_le",
    "FalconerThetaGauge.activeLinkedColumns_fiber_count_le",
    "FalconerThetaGauge.activeLinkedColumns_count_le",
    "FalconerThetaGauge.contDiff_orthogonalityRadialAmplitude",
    "FalconerThetaGauge.orthogonalityRadialAmplitude_eq_zero",
    "FalconerThetaGauge.tsupport_orthogonalityRadialAmplitude_subset",
    "FalconerThetaGauge.hasCompactSupport_orthogonalityRadialAmplitude",
    "FalconerThetaGauge.volume_tsupport_orthogonalityRadialAmplitude_le",
    "FalconerThetaGauge.norm_iteratedDeriv_maskedFrequencyCutoff_le_geometric",
    "FalconerThetaGauge.radialPolynomialBudget_le_sourceBudget",
    "FalconerThetaGauge.orthogonality_radial_ratio_le",
    "FalconerThetaGauge.orthogonality_radial_prefactor_le",
    "FalconerThetaGauge.orthogonality_radial_bound_le_terminal",
    "FalconerThetaGauge.norm_integral_orthogonalityRadialAmplitude_le_terminal",
    "FalconerThetaGauge.norm_integral_orthogonalityRadialAmplitude_le",
    "FalconerThetaGauge.norm_iteratedDeriv_mul_le_at",
    "FalconerThetaGauge.norm_iteratedDeriv_complex_square_le",
    "FalconerThetaGauge.norm_iteratedDeriv_scaled_frequencyCutoff_le",
    "FalconerThetaGauge.norm_iteratedDeriv_orthogonalityRadialAmplitude_le_on_support",
    "FalconerThetaGauge.norm_second_centers_sub_le_of_linked",
    "FalconerThetaGauge.linkedSecondColumns_count_le",
    "FalconerThetaGauge.linked_symbolActiveCell_mem_firstColumns",
    "FalconerThetaGauge.symbolActiveLinkedColumns_count_le",
    "FalconerThetaGauge.card_le_tubeCount",
    "FalconerThetaGauge.linkedAncestorColumns_count_le_tubeCount",
    "FalconerThetaGauge.linkedAncestorColumns_count_le_height",
    "FalconerThetaGauge.directionLineResidual_norm_eq_abs_inner_quarterTurn",
    "FalconerThetaGauge.abs_inner_change_direction_le",
    "FalconerThetaGauge.linked_witness_line_distance_le",
    "FalconerThetaGauge.linked_witness_width_budget",
    "FalconerThetaGauge.linked_centers_mem_witness_tube",
    "FalconerThetaGauge.ProfileChainState.finish_le_terminal_of_valid",
    "FalconerThetaGauge.regularMeasureExcess_bounds_unit",
    "FalconerThetaGauge.regularMeasureProfileBudget_bounds",
    "FalconerThetaGauge.actual_weighted_node_error_le_budget",
    "FalconerThetaGauge.actualProfileTreeError_le_profileBudget",
    "FalconerThetaGauge.actualProfileTreeError_le_small",
    "FalconerThetaGauge.actualProfileTreeTerminalEnergy_add_error_le_budget",
    "FalconerThetaGauge.profileMaskedDistanceHighShellEnergy_nonneg",
    "FalconerThetaGauge.normalizedShell_le_profileMaskedDistanceHighShellEnergy",
    "FalconerThetaGauge.profileDistanceStateEnergy_low_high",
    "FalconerThetaGauge.scalarHighDyadicIndices_nat",
    "FalconerThetaGauge.regularMeasureStateEnergy_low_high",
    "FalconerThetaGauge.regularMeasureHighShells_card_le_toleranceCount",
    "FalconerThetaGauge.profileInductionLevelVisits_initial",
    "FalconerThetaGauge.profileInductionVisits_initial",
    "FalconerThetaGauge.actualProfileTreeTerminalEnergy_le_budget",
    "FalconerThetaGauge.ScheduledSymbolData.ne_zero_implies_anchorCarrier",
    "FalconerThetaGauge.ne_zero_implies_next_passing_of_mem_scheduledSymbolClass",
    "FalconerThetaGauge.dyadicCenterBallIndexBox_four_radius_card",
    "FalconerThetaGauge.spaceSplittingNear_symm",
    "FalconerThetaGauge.spaceSplittingNear_mem_indexBoxes",
    "FalconerThetaGauge.spaceSplittingNear_row_card_le",
    "FalconerThetaGauge.spaceSplittingNear_column_card_le",
    "FalconerThetaGauge.maskedFourierPairCircleEnergy_eq",
    "FalconerThetaGauge.integrable_maskedFourierPairCircleEnergy",
    "FalconerThetaGauge.mass_mul_maskedCircularSpectrum",
    "FalconerThetaGauge.mass_mul_maskedCircularSpectrum_pair",
    "FalconerThetaGauge.mass_mul_maskedFourierEnergy",
    "FalconerThetaGauge.maskedFourierRadialWeight_nonneg",
    "FalconerThetaGauge.measurable_maskedFourierRadialWeight",
    "FalconerThetaGauge.integrable_maskedFourierRadialWeight",
    "FalconerThetaGauge.maskedFourierRadialWeight_eq_zero_of_nonpos",
    "FalconerThetaGauge.integral_maskedFourierRadialMeasure",
    "FalconerThetaGauge.orthogonalityRadialAmplitude_eq_real_weight",
    "FalconerThetaGauge.mass_mul_maskedFourierEnergy_radial",
    "FalconerThetaGauge.norm_maskedFourierArcPairAmplitude_sq",
    "FalconerThetaGauge.measurable_maskedFourierArcPairAmplitude",
    "FalconerThetaGauge.norm_maskedFourierArcPairAmplitude_le",
    "FalconerThetaGauge.memLp_maskedFourierArcPairAmplitude",
    "FalconerThetaGauge.maskedFourierAmplitude_eq_zero_of_inactive",
    "FalconerThetaGauge.sqrt_cutoff_mul_maskedFourierAmplitude_active",
    "FalconerThetaGauge.maskedFourierArcPairAmplitude_active",
    "FalconerThetaGauge.integrable_maskedFourierJointSquare",
    "FalconerThetaGauge.mass_mul_maskedFourierEnergy_joint",
    "FalconerThetaGauge.sum_norm_maskedFourierArcPairAmplitude_sq",
    "FalconerThetaGauge.sum_maskedFourierArcPairEnergy",
    "FalconerThetaGauge.maskedFourierArcPairEnergy_le_links",
    "FalconerThetaGauge.angularPartitionCount_mul_double_width_le",
    "FalconerThetaGauge.orthogonality_total_arc_error_le",
    "FalconerThetaGauge.sum_symbolActiveCellDescendants_mass_le",
    "FalconerThetaGauge.sum_symbolActiveCellPairs_mass_le",
    "FalconerThetaGauge.sum_unlinked_mass_products_le",
    "FalconerThetaGauge.maskedFourierArcPairEnergy_nonneg",
    "FalconerThetaGauge.sum_active_arc_energy_le_occupied",
    "FalconerThetaGauge.sum_occupied_arc_energy_eq",
    "FalconerThetaGauge.maskedFourierArcPairEnergy_le_orthogonality",
    "FalconerThetaGauge.mass_mul_maskedFourierEnergy_le_orthogonality",
    "FalconerThetaGauge.maskedFourierEnergy_le_orthogonality",
    "FalconerThetaGauge.integral_circle_eq_interval",
    "FalconerThetaGauge.orthogonalityCircleKernel_comp_angle",
    "FalconerThetaGauge.measurable_orthogonalityCircleAmplitude",
    "FalconerThetaGauge.measurable_orthogonalityCircleKernel",
    "FalconerThetaGauge.norm_orthogonalityCircleKernel",
    "FalconerThetaGauge.norm_orthogonalityCircleKernel_le_one",
    "FalconerThetaGauge.integral_norm_orthogonalityCircleKernel_le",
    "FalconerThetaGauge.norm_integral_orthogonalityCircleKernel_le",
    "FalconerThetaGauge.integral_orthogonalityCircleKernel_eq_angular",
    "FalconerThetaGauge.integrable_radial_mul_bounded",
    "FalconerThetaGauge.integrable_orthogonalityCircleKernel",
    "FalconerThetaGauge.integrable_orthogonalityTwoPair_integrand",
    "FalconerThetaGauge.orthogonalityTwoPairKernel_eq_radial_first",
    "FalconerThetaGauge.integrable_orthogonalityTwoPair_outer",
    "FalconerThetaGauge.orthogonalityTwoPairKernel_swap",
    "FalconerThetaGauge.integral_norm_orthogonalityRadialAmplitude_le",
    "FalconerThetaGauge.norm_orthogonalityTwoPairKernel_le_of_angular_cancel",
    "FalconerThetaGauge.orthogonalityCircleKernel_zero",
    "FalconerThetaGauge.orthogonality_radial_integrand_factorization",
    "FalconerThetaGauge.norm_orthogonalityTwoPairKernel_le_of_radial_cancel",
    "FalconerThetaGauge.orthogonality_circle_source_decay",
    "FalconerThetaGauge.norm_orthogonalityTwoPairKernel_angular_source",
    "FalconerThetaGauge.orthogonality_radialPhase_gt_half_of_center_failure",
    "FalconerThetaGauge.norm_orthogonalityTwoPairKernel_radial_source",
    "FalconerThetaGauge.norm_orthogonalityTwoPairKernel_unlinked",
    "FalconerThetaGauge.measurable_orthogonalityCircleKernel_joint",
    "FalconerThetaGauge.measurable_orthogonalityTwoPairKernel",
    "FalconerThetaGauge.norm_orthogonalityTwoPairKernel_le",
    "FalconerThetaGauge.integral_spatial_orthogonalityCircleKernel",
    "FalconerThetaGauge.maskedFourierArcPairAmplitude_cross_eq",
    "FalconerThetaGauge.integral_joint_orthogonalityCircleKernel_pair",
    "FalconerThetaGauge.measurable_orthogonalitySpatialCircleKernel",
    "FalconerThetaGauge.integrable_orthogonalitySpatialCircleKernel",
    "FalconerThetaGauge.integral_maskedFourierArcPair_cross_eq_spatial",
    "FalconerThetaGauge.ae_mem_four_carriers",
    "FalconerThetaGauge.norm_integral_maskedFourierArcPair_cross_unlinked",
    "FalconerThetaGauge.integrable_complex_cross_of_memLp_two",
    "FalconerThetaGauge.abs_integral_real_inner_le_norm_complex_cross",
    "FalconerThetaGauge.abs_integral_real_inner_maskedFourierArcPair_unlinked",
    "FalconerThetaGauge.integral_preparedInverseCircleKernelSeries_sq_le",
    "FalconerThetaGauge.integrable_maskedDistancePairFourierIntegrand",
    "FalconerThetaGauge.angularScalarFourier_maskedDistance_eq_integral",
    "FalconerThetaGauge.isFiniteMeasure_maskedDistance",
    "FalconerThetaGauge.norm_integral_sub_le_const",
    "FalconerThetaGauge.integrable_spatial_preparedInverseCircleKernelSeries",
    "FalconerThetaGauge.norm_maskedDistance_mattila_inversion_error",
    "FalconerThetaGauge.integrable_norm_tsum_mul_sq",
    "FalconerThetaGauge.integrableOn_preparedInverseCircleKernelSeries_sq",
    "FalconerThetaGauge.integral_sq_le_of_uniform_error",
    "FalconerThetaGauge.norm_preparedCircleInversionConstant_sq",
    "FalconerThetaGauge.integral_builtMaskedDistance_window_le",
    "FalconerThetaGauge.norm_angularScalarFourier_neg",
    "FalconerThetaGauge.scalarDyadicFourierShellIntegral_le_twice_window",
    "FalconerThetaGauge.mattila_shell_error_budget",
    "FalconerThetaGauge.isFiniteMeasure_builtMaskedDistanceMeasure",
    "FalconerThetaGauge.builtMaskedDistance_mattila_shell_estimate",
    "FalconerThetaGauge.builtMaskedDistanceMeasure_eq_level",
    "FalconerThetaGauge.builtMaskedDistance_mattila_shell_normalized_estimate",
    "FalconerThetaGauge.levelMaskedDistance_mattila_cells_estimate",
    "FalconerThetaGauge.profileMaskedDistanceHighShellEnergy_le_fourier_state",
    "FalconerThetaGauge.regularMeasureStateEnergy_moveTwo_mattila",
    "FalconerThetaGauge.dyadicRadius_antitone",
    "FalconerThetaGauge.dyadicRadius_add",
    "FalconerThetaGauge.dist_dyadicCenters_le_point_dist",
    "FalconerThetaGauge.dist_points_le_dyadicCenters",
    "FalconerThetaGauge.spaceSplittingFar_distance_gt",
    "FalconerThetaGauge.spaceSplittingFar_comparable_distance_gt",
    "FalconerThetaGauge.separatedDyadicCells_of_distance_bin",
    "FalconerThetaGauge.spaceSplitting_comparable_bin_separated",
    "FalconerThetaGauge.spaceSplitting_distance_bin_depth_bounds",
    "FalconerThetaGauge.norm_spaceSplittingCircleIntegral_le",
    "FalconerThetaGauge.integral_spaceSplittingCircleIntegral",
    "FalconerThetaGauge.spaceSplittingCircleIntegral_eq_interval",
    "FalconerThetaGauge.spaceSplittingCircleIntegral_stationary",
    "FalconerThetaGauge.iteratedDeriv_builtSymbolAngularAmplitude_eq_zero_of_not_passing",
    "FalconerThetaGauge.iteratedDeriv_builtSymbolPairAngularAmplitude_eq_zero_of_not_passing",
    "FalconerThetaGauge.stationaryPhaseOperators_pair_eq_zero_of_not_passing",
    "FalconerThetaGauge.stationaryPhaseOperators_pair_ne_zero_implies_passing",
    "FalconerThetaGauge.unitCircleOfAngle_radialAngle_difference",
    "FalconerThetaGauge.stationaryPhaseCoefficients_ne_zero_implies_passingPair",
    "FalconerThetaGauge.contDiffAt_real_zpow",
    "FalconerThetaGauge.iteratedDeriv_real_zpow",
    "FalconerThetaGauge.iteratedDeriv_ofReal_zpow",
    "FalconerThetaGauge.spaceSplittingRadialAmplitude_eq_zero",
    "FalconerThetaGauge.tsupport_spaceSplittingRadialAmplitude_subset",
    "FalconerThetaGauge.hasCompactSupport_spaceSplittingRadialAmplitude",
    "FalconerThetaGauge.contDiff_spaceSplittingRadialAmplitude",
    "FalconerThetaGauge.norm_iteratedDeriv_ofReal_zpow_le_two",
    "FalconerThetaGauge.real_zpow_le_dyadic_window",
    "FalconerThetaGauge.norm_iteratedDeriv_scaled_cutoff_le_exact",
    "FalconerThetaGauge.norm_iteratedDeriv_two_mul_le",
    "FalconerThetaGauge.norm_deriv_ofReal_zpow",
    "FalconerThetaGauge.norm_secondDeriv_ofReal_zpow_le",
    "FalconerThetaGauge.spaceSplittingRadialBound_pos",
    "FalconerThetaGauge.norm_secondDeriv_cutoff_zpow_le",
    "FalconerThetaGauge.norm_spaceSplittingRadialAmplitude_le_on_support",
    "FalconerThetaGauge.norm_secondDeriv_spaceSplittingRadialAmplitude_le_on_support",
    "FalconerThetaGauge.volume_tsupport_spaceSplittingRadialAmplitude_le",
    "FalconerThetaGauge.spaceSplittingRadialMoment_eq_positive_integral",
    "FalconerThetaGauge.norm_spaceSplittingRadialMoment_le_trivial",
    "FalconerThetaGauge.norm_spaceSplittingRadialMoment_le_second",
    "FalconerThetaGauge.scalar_second_decay_le_kernel",
    "FalconerThetaGauge.norm_spaceSplittingRadialMoment_le_kernel",
    "FalconerThetaGauge.stationary_orders_natAbs_le",
    "FalconerThetaGauge.stationary_orders_abs_le",
    "FalconerThetaGauge.spaceSplittingRadialBound_orders_le",
    "FalconerThetaGauge.norm_spaceSplittingRadialMoment_orders_le",
    "FalconerThetaGauge.profileScheduledTests_right_split_projection",
    "FalconerThetaGauge.profileScheduledTests_short_at_finish",
    "FalconerThetaGauge.profileDistanceStateEnergy_le_linearization",
    "FalconerThetaGauge.regularMeasureStateEnergy_moveOne",
    "FalconerThetaGauge.ProfileMoveChain.append_state_final",
    "FalconerThetaGauge.ProfileMoveChain.append_levelIncrement_before",
    "FalconerThetaGauge.ProfileMoveChain.append_levelIncrement_last",
    "FalconerThetaGauge.ProfileMoveChain.append_maskLevel",
    "FalconerThetaGauge.ProfileMoveChain.append_multiplier_before",
    "FalconerThetaGauge.ProfileMoveChain.append_multiplier_last",
    "FalconerThetaGauge.ProfileMoveChain.append_multiplierProduct",
    "FalconerThetaGauge.ProfileMoveChain.multiplierProduct_nonneg",
    "FalconerThetaGauge.multiset_sum_map_finset_sum",
    "FalconerThetaGauge.multiset_sum_map_filter_eq_ite",
    "FalconerThetaGauge.profileInductionVisits_telescope",
    "FalconerThetaGauge.profileTransitionMultiplier",
    "FalconerThetaGauge.profileTransitionLevelIncrement",
    "FalconerThetaGauge.profileTransitionMultiplier_nonneg",
    "FalconerThetaGauge.ProfileChainMove.upperMultiplier_eq_transition",
    "FalconerThetaGauge.ProfileChainMove.levelIncrement_eq_transition",
    "FalconerThetaGauge.regularMeasureChildrenEnergy",
    "FalconerThetaGauge.regularMeasureChildrenEnergy_nonneg",
    "FalconerThetaGauge.regularMeasureChildrenEnergy_right_split",
    "FalconerThetaGauge.regularMeasureChildrenEnergy_left_split",
    "FalconerThetaGauge.regularMeasureStateEnergy_discrepancy_recurrence",
    "FalconerThetaGauge.regularMeasureStateEnergy_refinement_recurrence",
    "FalconerThetaGauge.ProfileMoveChain.children_sum",
    "FalconerThetaGauge.actualProfileNodeEnergy",
    "FalconerThetaGauge.actualProfileNodeEnergy_root",
    "FalconerThetaGauge.actualProfileNodeEnergy_children",
    "FalconerThetaGauge.regularMeasureStateEnergy_le_actual_tree",
    "FalconerThetaGauge.regularMeasureStateEnergy_le_tree_budget",
    "FalconerThetaGauge.regularMeasureChildrenEnergy_space_split",
    "FalconerThetaGauge.ActualSpaceSplittingRecurrence",
    "FalconerThetaGauge.regularMeasureStateEnergy_recurrence_of_space_split",
    "FalconerThetaGauge.regularMeasureStateEnergy_tree_budget_of_space_split",
    "FalconerThetaGauge.profileRemainingTests_at_base",
    "FalconerThetaGauge.profileScheduledTests_left_split_tube",
    "FalconerThetaGauge.profileSplitPoint_left_shell_geometry",
    "FalconerThetaGauge.directionalLevelWidth_ge_one",
    "FalconerThetaGauge.sum_occupiedCellPairs_normalized_mass_le_one",
    "FalconerThetaGauge.occupiedCellDescendant_mem_occupied",
    "FalconerThetaGauge.sum_maskedFourierEnergy_remaining_le_refined_state",
    "FalconerThetaGauge.profileRemainingTests_ordered",
    "FalconerThetaGauge.profileFourierStateEnergy_le_orthogonality",
    "FalconerThetaGauge.regularMeasureStateEnergy_moveTwo_orthogonality",
    "FalconerThetaGauge.moveTwo_high_multiplier_le",
    "FalconerThetaGauge.moveTwo_high_shell_error_le",
    "FalconerThetaGauge.regularMeasureStateEnergy_moveTwo_raw",
    "FalconerThetaGauge.regularMeasureStateEnergy_moveTwo",
    "FalconerThetaGauge.profileRemainingTests_refinement_tube",
    "FalconerThetaGauge.profileRemainingTests_refinement_geometry",
    "FalconerThetaGauge.profileRemainingTests_length_le_longest",
    "FalconerThetaGauge.profileRemainingTests_refinement_real_geometry",
    "FalconerThetaGauge.profileHeight_refinement_le_parent",
    "FalconerThetaGauge.regularMeasureStateEnergy_moveThree",
    "FalconerThetaGauge.regularMeasureStateEnergy_moveThree_le_uniform_error",
    "FalconerThetaGauge.scalarFourierAnnulusIntegral_eq_twice_window",
    "FalconerThetaGauge.builtMaskedDistance_mattila_annulus_estimate",
    "FalconerThetaGauge.pairDirection_mem_arc_of_prepared_balls",
    "FalconerThetaGauge.ParameterFacts.mattila_root_gap",
    "FalconerThetaGauge.restrict_eq_self_of_probability_mass_one",
    "FalconerThetaGauge.preparedRoot_mattila_annulus_estimate",
    "FalconerThetaGauge.regularDyadicPartMeasure_mass_one",
    "FalconerThetaGauge.preparedRegularParts_mattila_annulus_estimate",
    "FalconerThetaGauge.dyadicFrequencyAverage_mul_le_sqrt",
    "FalconerThetaGauge.maskedFourierEnergy_le_sqrt_self",
    "FalconerThetaGauge.scheduledFourierEnergySup_le_sqrt_self",
    "FalconerThetaGauge.maskedCircularSpectrum_probability_carrier_eq",
    "FalconerThetaGauge.maskedFourierEnergy_probability_carrier_eq",
    "FalconerThetaGauge.scheduledFourierEnergySup_probability_carrier_eq",
    "FalconerThetaGauge.measurableSet_mattila_unitSquare",
    "FalconerThetaGauge.preparedRegularParts_mattila_annulus_le_self_energies",
    "FalconerThetaGauge.filteredCrossDistanceMeasure_restrict_carriers",
    "FalconerThetaGauge.filteredCrossDistanceMeasure_congr_on_carriers",
    "FalconerThetaGauge.filteredCrossDistanceMeasure_sum",
    "FalconerThetaGauge.filteredCrossDistanceMeasure_smul",
    "FalconerThetaGauge.restrict_eq_mass_smul_normalizedRestrict",
    "FalconerThetaGauge.filteredCrossDistanceMeasure_finite_carrier_mixture",
    "FalconerThetaGauge.regularRetainedCarrier",
    "FalconerThetaGauge.regularRetainedMass",
    "FalconerThetaGauge.regularRetainedProbability",
    "FalconerThetaGauge.regularRetainedSymbol",
    "FalconerThetaGauge.regularFilteredDistanceMeasure",
    "FalconerThetaGauge.measurableSet_regularRetainedCarrier",
    "FalconerThetaGauge.regularRetainedCarrier_pairwiseDisjoint",
    "FalconerThetaGauge.regularRetainedMass_ne_zero",
    "FalconerThetaGauge.regularRetainedProbability_probability",
    "FalconerThetaGauge.regularFilterCarrier_eq_iUnion",
    "FalconerThetaGauge.regularDirectionalFilter_symbol_eq_retainedSymbol",
    "FalconerThetaGauge.regularDirectionalFilter_symbol_eq_zero_off_carrier",
    "FalconerThetaGauge.regularFilteredDistanceMeasure_eq_piece_mixture",
    "FalconerThetaGauge.sum_regularRetainedMass_le_one",
    "FalconerThetaGauge.integrable_scalar_character",
    "FalconerThetaGauge.angularScalarFourier_finite_mixture",
    "FalconerThetaGauge.integrableOn_scalarFourierAnnulus",
    "FalconerThetaGauge.scalarFourierAnnulusIntegral_finite_mixture_le",
    "FalconerThetaGauge.scalarFourierAnnulusIntegral_subprobability_mixture_le",
    "FalconerThetaGauge.regularRetainedPairMeasure",
    "FalconerThetaGauge.regularRetainedPairMass",
    "FalconerThetaGauge.regularRetainedMass_ne_top",
    "FalconerThetaGauge.sum_regularRetainedMass_toReal_le_one",
    "FalconerThetaGauge.regularRetainedPairMass_ne_top",
    "FalconerThetaGauge.sum_regularRetainedPairMass_toReal_le_one",
    "FalconerThetaGauge.regularRetainedSymbol_mem_Icc",
    "FalconerThetaGauge.isFiniteMeasure_regularRetainedPairMeasure",
    "FalconerThetaGauge.regularFilteredDistanceMeasure_annulus_le_piece_annuli",
    "FalconerThetaGauge.regularRetainedRootSelfEnergy",
    "FalconerThetaGauge.regularRetainedRootSelfEnergy_nonneg",
    "FalconerThetaGauge.regularFilteredDistanceMeasure_annulus_le_weighted_self_energies",
    "FalconerThetaGauge.finite_pair_weighted_energy_sum",
    "FalconerThetaGauge.regularRetainedRootSqrtEnergyAverage",
    "FalconerThetaGauge.regularFilteredDistanceMeasure_annulus_le_sqrt_energy_averages",
    "FalconerThetaGauge.norm_stationaryPhaseOperator_le_of_regular",
    "FalconerThetaGauge.norm_stationaryPhaseConjugateOperator_le_of_regular",
    "FalconerThetaGauge.norm_stationaryPhaseOperator_builtPair_le",
    "FalconerThetaGauge.norm_stationaryPhaseConjugateOperator_builtPair_le",
    "FalconerThetaGauge.stationary_coefficient_scaled_le_geometric",
    "FalconerThetaGauge.nat_successor_sq_le_three_two_pow",
    "FalconerThetaGauge.sum_geometric_quarter_le_two",
    "FalconerThetaGauge.sum_successor_sq_geometric_quarter_le_six",
    "FalconerThetaGauge.stationary_order_double_geometric_sum_le_fifty",
    "FalconerThetaGauge.two_stationary_order_double_geometric_sum_le_hundred",
    "FalconerThetaGauge.dyadic_stationary_order_power",
    "FalconerThetaGauge.spaceSplittingOppositeTerm",
    "FalconerThetaGauge.norm_spaceSplittingOppositeTerm_le",
    "FalconerThetaGauge.spaceSplittingOppositeRadialSeries",
    "FalconerThetaGauge.norm_stationaryPhaseOperator_pair_scale",
    "FalconerThetaGauge.norm_stationaryPhaseConjugateOperator_pair_scale",
    "FalconerThetaGauge.norm_spaceSplittingOppositeRadialSeries_le",
    "FalconerThetaGauge.spaceSplittingBuiltOppositeSeries",
    "FalconerThetaGauge.stationaryPhaseCoefficients_eq_zero_of_not_passingPair",
    "FalconerThetaGauge.spaceSplittingBuiltOppositeSeries_eq_zero_of_not_passing",
    "FalconerThetaGauge.norm_spaceSplittingBuiltOppositeSeries_le_passing_kernel",
    "FalconerThetaGauge.norm_iteratedDeriv_mul_le_contDiffAt",
    "FalconerThetaGauge.norm_iteratedDeriv_ofReal_zpow_le_scale",
    "FalconerThetaGauge.norm_iteratedDeriv_spaceSplittingRadialAmplitude_le",
    "FalconerThetaGauge.norm_spaceSplittingRadialMoment_le_linear",
    "FalconerThetaGauge.stationary_orders_abs_le_two_order",
    "FalconerThetaGauge.norm_spaceSplittingEqualSignMoment_le",
    "FalconerThetaGauge.spaceSplittingJointAmplitude",
    "FalconerThetaGauge.measurable_spaceSplittingJointAmplitude",
    "FalconerThetaGauge.norm_spaceSplittingJointAmplitude_le",
    "FalconerThetaGauge.memLp_spaceSplittingJointAmplitude",
    "FalconerThetaGauge.spaceSplittingJointAmplitude_occupiedCellDescendants",
    "FalconerThetaGauge.mass_mul_maskedFourierEnergy_le_near_schur",
    "FalconerThetaGauge.weightedCrossDistanceMeasure_absolutelyContinuous_of_space_split",
    "FalconerThetaGauge.exists_parameter_constant_threshold",
    "FalconerThetaGauge.weightedCrossDistanceMeasure_absolutelyContinuous_of_space_split_all_scales",
    "FalconerThetaGauge.regularFilteredDistanceMeasure_shell_bound_of_space_split",
    "FalconerThetaGauge.summable_dyadic_gain_power",
    "FalconerThetaGauge.dyadicMeasureFourierEnergy_eq_scalarFourierAnnulusIntegral",
    "FalconerThetaGauge.ParameterFacts",
    "FalconerThetaGauge.rootPieceFourierEnergy_le_entry_state",
    "FalconerThetaGauge.dyadicCube_zero_eq_unitSquare",
    "FalconerThetaGauge.zero_mem_occupiedUnitCells",
    "FalconerThetaGauge.regularMeasurePieceTests_filter_entry",
    "FalconerThetaGauge.scheduledFourierEnergySup_piece_le_entry_state",
    "FalconerThetaGauge.sum_maskedFourierEnergy_piece_le_entry_state",
    "FalconerThetaGauge.regularRetainedRootSelfEnergy_le_entry_state",
    "FalconerThetaGauge.entryShellSelfEnergyBound",
    "FalconerThetaGauge.entryShellSelfEnergyBound_nonneg",
    "FalconerThetaGauge.regularRetainedRootSelfEnergy_le_shell_bound_of_entry_state_bound",
    "FalconerThetaGauge.regularRetainedRootSqrtEnergyAverage_le_sqrt",
    "FalconerThetaGauge.regularFilteredDistanceMeasure_shell_bound_of_entry_state_bounds",
    "FalconerThetaGauge.spaceSplittingAveragedCircleKernel",
    "FalconerThetaGauge.spaceSplittingAveragedCircleKernel_eq_radial",
    "FalconerThetaGauge.measurable_maskedFourierPairKernel_joint",
    "FalconerThetaGauge.measurable_spaceSplittingCircleIntegral_joint",
    "FalconerThetaGauge.measurable_spaceSplittingAveragedCircleKernel",
    "FalconerThetaGauge.norm_spaceSplittingAveragedCircleKernel_le",
    "FalconerThetaGauge.integrable_spaceSplittingAveragedCircleKernel",
    "FalconerThetaGauge.spaceSplittingSpatialCircleKernel",
    "FalconerThetaGauge.measurable_spaceSplittingSpatialCircleKernel",
    "FalconerThetaGauge.norm_spaceSplittingSpatialCircleKernel_le_one",
    "FalconerThetaGauge.integrable_spaceSplittingSpatialCircleKernel",
    "FalconerThetaGauge.integral_joint_spaceSplittingSpatialCircleKernel",
    "FalconerThetaGauge.spaceSplittingJointAmplitude_cross_eq_spatial",
    "FalconerThetaGauge.integral_spaceSplittingJointAmplitude_cross_eq_spatial",
    "FalconerThetaGauge.integral_spaceSplittingJointAmplitude_inner_eq_spatial",
    "FalconerThetaGauge.spaceSplittingAveragedCircleKernel_eq_full_line",
    "FalconerThetaGauge.maskedFourierRadialMeasure_real_univ_le",
    "FalconerThetaGauge.norm_spaceSplittingAveragedCircleKernel_le_source",
    "FalconerThetaGauge.abs_integral_spaceSplittingJointAmplitude_inner_le_integral_norm",
    "FalconerThetaGauge.abs_integral_spaceSplittingJointAmplitude_inner_le_lintegral_norm",
    "FalconerThetaGauge.regularRetainedEntryStateEnergy_le_of_space_split",
    "FalconerThetaGauge.regularRetainedEntryStateEnergy_le_source_of_space_split",
    "FalconerThetaGauge.profileNearStart_strict_geometry",
    "FalconerThetaGauge.profileScheduledTests_subset_remaining_for_far",
    "FalconerThetaGauge.scheduledDistanceEnergy_remaining_le_far_state",
    "FalconerThetaGauge.regularRemainingDistanceEnergy_le_far_child",
    "FalconerThetaGauge.spaceSplitting_stationary_prefactor",
    "FalconerThetaGauge.spaceSplitting_stationary_phase_opposite",
    "FalconerThetaGauge.spaceSplitting_stationary_phase_equal_positive",
    "FalconerThetaGauge.spaceSplitting_stationary_phase_equal_negative",
    "FalconerThetaGauge.spaceSplitting_stationary_radial_power",
    "FalconerThetaGauge.spaceSplittingStationaryRadialTerm",
    "FalconerThetaGauge.integrable_spaceSplittingStationaryRadialTerm",
    "FalconerThetaGauge.integral_spaceSplittingStationaryRadialTerm",
    "FalconerThetaGauge.spaceSplitting_stationary_radial_prefactor",
    "FalconerThetaGauge.spaceSplittingEqualSignRadialSeries",
    "FalconerThetaGauge.spaceSplittingStationaryMain_eq_sum",
    "FalconerThetaGauge.spaceSplitting_stationary_product_term",
    "FalconerThetaGauge.spaceSplittingStationaryProductTerms",
    "FalconerThetaGauge.spaceSplittingStationaryProductTerms_eq_zero",
    "FalconerThetaGauge.orthogonalityRadialAmplitude_mul_stationaryMain_product",
    "FalconerThetaGauge.integrable_spaceSplittingStationaryProductTerms",
    "FalconerThetaGauge.integral_spaceSplittingStationaryProductTerms",
    "FalconerThetaGauge.integral_orthogonalityRadialAmplitude_mul_stationaryMain_product",
    "FalconerThetaGauge.norm_spaceSplitting_equal_coefficient_moment_le",
    "FalconerThetaGauge.spaceSplitting_equal_prefactor_le_terminal",
    "FalconerThetaGauge.norm_spaceSplitting_equal_coefficient_moment_le_source",
    "FalconerThetaGauge.two_stationary_count_square_le_terminal",
    "FalconerThetaGauge.spaceSplittingBuiltEqualSignSeries",
    "FalconerThetaGauge.norm_spaceSplittingBuiltEqualSignSeries_le_source",
    "FalconerThetaGauge.norm_spaceSplittingStationaryMain_product_integral_le_source",
    "FalconerThetaGauge.norm_spaceSplittingAveragedCircleKernel_caseB_le_source",
    "FalconerThetaGauge.iteratedDeriv_real_rpow",
    "FalconerThetaGauge.iteratedDeriv_ofReal_rpow",
    "FalconerThetaGauge.spaceSplittingRealPowerAmplitude",
    "FalconerThetaGauge.spaceSplittingRealPowerAmplitude_eq_zero",
    "FalconerThetaGauge.tsupport_spaceSplittingRealPowerAmplitude_subset",
    "FalconerThetaGauge.hasCompactSupport_spaceSplittingRealPowerAmplitude",
    "FalconerThetaGauge.contDiff_spaceSplittingRealPowerAmplitude",
    "FalconerThetaGauge.volume_tsupport_spaceSplittingRealPowerAmplitude_le",
    "FalconerThetaGauge.real_rpow_le_dyadic_window",
    "FalconerThetaGauge.norm_iteratedDeriv_ofReal_rpow_le_scale",
    "FalconerThetaGauge.caseA_radial_exponent_abs_le",
    "FalconerThetaGauge.caseA_radial_power_window_le",
    "FalconerThetaGauge.norm_iteratedDeriv_spaceSplittingRealPowerAmplitude_le",
    "FalconerThetaGauge.spaceSplittingCaseAAmplitude",
    "FalconerThetaGauge.spaceSplittingCaseABound",
    "FalconerThetaGauge.caseA_radialWindowCoefficient_le",
    "FalconerThetaGauge.norm_iteratedDeriv_spaceSplittingCaseAAmplitude_le",
    "FalconerThetaGauge.spaceSplittingCaseARadialMoment",
    "FalconerThetaGauge.norm_spaceSplittingCaseARadialMoment_le_linear",
    "FalconerThetaGauge.spaceSplittingCaseA_phase_abs_ge",
    "FalconerThetaGauge.norm_spaceSplittingCaseARadialMoment_le_spatial",
    "FalconerThetaGauge.spaceSplitting_mask_factor_le",
    "FalconerThetaGauge.spaceSplitting_symbol_scale_squared_shift_le",
    "FalconerThetaGauge.spaceSplitting_polynomial_le_sourceBudget",
    "FalconerThetaGauge.spaceSplitting_coefficient_polynomial_le_sourceBudget",
    "FalconerThetaGauge.spaceSplitting_remainderBase_eq",
    "FalconerThetaGauge.spaceSplitting_inv_frequency_distance_le",
    "FalconerThetaGauge.spaceSplitting_inv_dyadic_distance_le",
    "FalconerThetaGauge.spaceSplitting_remainder_ratio_le",
    "FalconerThetaGauge.spaceSplitting_coefficient_scale_le",
    "FalconerThetaGauge.spaceSplitting_coefficient_scale_le_quarter",
    "FalconerThetaGauge.spaceSplitting_phase_scale_ge_one",
    "FalconerThetaGauge.spaceSplitting_remainderBase_le_terminal",
    "FalconerThetaGauge.spaceSplitting_decay_ratio_pow_le",
    "FalconerThetaGauge.spaceSplitting_stationary_sqrt_le_three",
    "FalconerThetaGauge.spaceSplitting_stationary_remainder_le",
    "FalconerThetaGauge.spaceSplittingStationaryMain",
    "FalconerThetaGauge.norm_spaceSplittingCircleIntegral_sub_stationary_le_source",
    "FalconerThetaGauge.spaceSplitting_linear_polynomial_le_sourceBudget",
    "FalconerThetaGauge.spaceSplitting_linear_ratio_le",
    "FalconerThetaGauge.spaceSplitting_linear_ratio_pow_le",
    "FalconerThetaGauge.spaceSplitting_caseA_bound_coefficient_eq",
    "FalconerThetaGauge.norm_spaceSplittingCaseA_coefficient_moment_le",
    "FalconerThetaGauge.spaceSplitting_caseA_prefactor_le_terminal",
    "FalconerThetaGauge.norm_spaceSplittingCaseA_coefficient_moment_le_source",
    "FalconerThetaGauge.spaceSplitting_caseA_real_factor_eq",
    "FalconerThetaGauge.spaceSplittingCaseAStationaryTerm",
    "FalconerThetaGauge.spaceSplittingCaseAStationaryTerm_eq_realPower",
    "FalconerThetaGauge.spaceSplittingCaseAProductIntegrand",
    "FalconerThetaGauge.integrable_spaceSplittingCaseAProductIntegrand",
    "FalconerThetaGauge.integral_spaceSplittingCaseAAmplitude_circle_eq",
    "FalconerThetaGauge.integrable_spaceSplittingCaseAStationaryTerm_circle",
    "FalconerThetaGauge.integral_spaceSplittingCaseAStationaryTerm_circle_eq",
    "FalconerThetaGauge.norm_integral_spaceSplittingCaseAStationaryTerm_circle_le_source",
    "FalconerThetaGauge.orthogonalityRadialAmplitude_mul_spaceSplittingStationaryMain_eq",
    "FalconerThetaGauge.integral_spaceSplittingStationaryMain_circle_eq_sum",
    "FalconerThetaGauge.integrable_spaceSplittingStationaryMain_circle",
    "FalconerThetaGauge.spaceSplitting_caseA_order_prefactor_le_terminal",
    "FalconerThetaGauge.norm_integral_spaceSplittingStationaryMain_caseA_le_source",
    "FalconerThetaGauge.stronglyMeasurable_spaceSplittingCircleIntegral",
    "FalconerThetaGauge.integrable_spaceSplittingCircleIntegral_radial_pair",
    "FalconerThetaGauge.norm_integral_spaceSplittingCircle_sub_main_le_source",
    "FalconerThetaGauge.spaceSplitting_integrated_stationary_error_le_terminal",
    "FalconerThetaGauge.norm_spaceSplittingAveragedCircleKernel_caseA_le_source",
    "FalconerThetaGauge.spaceSplittingAveragedCircleKernel_swap",
    "FalconerThetaGauge.norm_spaceSplittingAveragedCircleKernel_caseA_reverse_le_source",
    "FalconerThetaGauge.dyadic_scalar_kernel_toReal_le",
    "FalconerThetaGauge.dyadic_scalar_kernel_toReal_le_normalized",
    "FalconerThetaGauge.spaceSplittingWeightedKernel",
    "FalconerThetaGauge.measurable_spaceSplittingWeightedKernel",
    "FalconerThetaGauge.lintegral_spaceSplittingWeightedKernel_eq",
    "FalconerThetaGauge.separatedDyadicCells_symm",
    "FalconerThetaGauge.separatedPartnerIndexBox_card",
    "FalconerThetaGauge.separatedDyadicCells_partner_card_le",
    "FalconerThetaGauge.spaceSplittingSeparatedPairs",
    "FalconerThetaGauge.sum_sqrt_mass_spaceSplittingSeparatedPairs_le",
    "FalconerThetaGauge.spaceSplittingRegroupingConstant",
    "FalconerThetaGauge.spaceSplittingRegroupingConstant_le_source",
    "FalconerThetaGauge.isFiniteMeasure_passingWeightedDistanceMeasure_of_separatedCells",
    "FalconerThetaGauge.spaceSplittingWeightedKernel_toReal_le_energy",
    "FalconerThetaGauge.sqrt_mass_energy_product_le",
    "FalconerThetaGauge.spaceSplittingDistanceMaximum",
    "FalconerThetaGauge.real_mass_pair_pos_of_mem_spaceSplittingSeparatedPairs",
    "FalconerThetaGauge.spaceSplitting_regrouped_kernel_le",
    "FalconerThetaGauge.scalarBinningKernel_dyadic",
    "FalconerThetaGauge.spaceSplittingWeightedKernel_eq_ofReal",
    "FalconerThetaGauge.ofReal_norm_spaceSplittingBuiltOppositeSeries_le",
    "FalconerThetaGauge.restrict_cellUnion_eq_sum",
    "FalconerThetaGauge.restrict_dyadicCube_eq_sum_occupiedCellDescendants",
    "FalconerThetaGauge.prod_finsetSum_measure",
    "FalconerThetaGauge.prod_restrict_dyadicCube_eq_sum_occupiedCellDescendants",
    "FalconerThetaGauge.lintegral_prod_finsetSum_measure",
    "FalconerThetaGauge.ae_mem_cellUnion_occupiedCellDescendants",
    "FalconerThetaGauge.exists_spaceSplitting_distance_bin",
    "FalconerThetaGauge.exists_spaceSplitting_distance_bin_of_far",
    "FalconerThetaGauge.spaceSplittingSeparatedCarrier",
    "FalconerThetaGauge.measurableSet_spaceSplittingSeparatedCarrier",
    "FalconerThetaGauge.spaceSplittingSeparatedCarrier_subset_root",
    "FalconerThetaGauge.restrict_spaceSplittingSeparatedCarrier_eq_sum",
    "FalconerThetaGauge.lintegral_restrict_spaceSplittingSeparatedCarriers_eq_sum",
    "FalconerThetaGauge.spaceSplittingRootFourMeasure",
    "FalconerThetaGauge.spaceSplittingFarComparableSet",
    "FalconerThetaGauge.measurableSet_spaceSplittingFarComparableSet",
    "FalconerThetaGauge.ae_spaceSplittingFarComparable_mem_depth_carrier",
    "FalconerThetaGauge.restrict_spaceSplittingFarComparable_le_depth_sum",
    "FalconerThetaGauge.lintegral_spaceSplittingFarComparable_le_depth_sum",
    "FalconerThetaGauge.lintegral_spaceSplittingWeightedKernel_ne_top",
    "FalconerThetaGauge.spaceSplittingDepthKernelSum",
    "FalconerThetaGauge.spaceSplittingDepthKernelSum_ne_top",
    "FalconerThetaGauge.spaceSplittingDepthKernelSum_toReal_le",
    "FalconerThetaGauge.spaceSplitting_far_kernel_toReal_le",
    "FalconerThetaGauge.ae_maskedFourierRadialMeasure_window",
    "FalconerThetaGauge.measurable_spaceSplittingStationaryMain",
    "FalconerThetaGauge.norm_circle_product_sub_stationary_product_le",
    "FalconerThetaGauge.norm_averaged_circle_product_sub_stationary_product_le",
    "FalconerThetaGauge.norm_spaceSplittingAveragedCircleKernel_sub_stationaryProduct_le_source",
)
DECLARATION_NAME = re.compile(r"[A-Za-z_][A-Za-z_0-9']*(?:\.[A-Za-z_][A-Za-z_0-9']*)*")
AXIOM_REPORT = re.compile(
    r"^'(?P<name>[^']+)' (?:does not depend on any axioms|"
    r"depends on axioms: \[(?P<axioms>[^\]]*)\])$"
)


def audit():
    config = json.loads((ROOT / "comparator.json").read_text(encoding="utf-8"))
    if not isinstance(config, dict):
        raise ValueError("comparator.json must contain one JSON object")
    targets = config.get("theorem_names")
    if not isinstance(targets, list) or MAIN_THEOREM not in targets:
        raise ValueError(f"comparator.json must select {MAIN_THEOREM}")
    if not all(isinstance(name, str) and DECLARATION_NAME.fullmatch(name) for name in targets):
        raise ValueError("comparator.json contains an invalid theorem name")
    axioms = config.get("permitted_axioms")
    if not isinstance(axioms, list) or not all(isinstance(name, str) for name in axioms):
        raise ValueError("comparator.json must contain a list of permitted axiom names")
    if set(axioms) != STANDARD_AXIOMS:
        raise ValueError("comparator.json must permit exactly the three standard Lean axioms")
    declarations = list(dict.fromkeys([*FOUNDATIONS, *targets]))

    # Lean emits structured diagnostic messages. Parse these rather than looking
    # for source words: a proof can hide sorryAx in a transitive dependency.
    with tempfile.TemporaryDirectory(prefix="theta-gauge-proof-status-") as directory:
        source = Path(directory) / "Audit.lean"
        source.write_text(
            "import Solution\n" + "".join(f"#print axioms {name}\n" for name in declarations),
            encoding="utf-8",
        )
        process = subprocess.run(
            ["lake", "env", "lean", "--json", str(source)],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=180,
            check=False,
        )

    reports = {}
    diagnostics = []
    for line in process.stdout.splitlines():
        if not line.strip():
            continue
        try:
            message = json.loads(line)
        except json.JSONDecodeError as error:
            raise ValueError(f"Lean emitted an unrecognized diagnostic: {line}") from error
        if not isinstance(message, dict):
            raise ValueError("Lean emitted a non-object diagnostic")
        data = message.get("data", "")
        if not isinstance(data, str):
            raise ValueError("Lean emitted a non-text diagnostic")
        if message.get("severity") == "error":
            diagnostics.append(data)
        match = AXIOM_REPORT.fullmatch(data.strip())
        if match is None:
            continue
        name = match.group("name")
        if name in reports:
            raise ValueError(f"Lean emitted duplicate axiom reports for {name}")
        axioms = sorted(
            axiom.strip() for axiom in (match.group("axioms") or "").split(",") if axiom.strip()
        )
        reports[name] = {
            "axioms": axioms,
            "forbidden_axioms": sorted(set(axioms) - STANDARD_AXIOMS),
        }
    if process.returncode != 0 or diagnostics:
        details = "\n".join(diagnostics) or process.stderr.strip() or process.stdout.strip()
        raise ValueError(f"Lean could not complete the axiom audit (exit {process.returncode}): {details}")
    missing = set(declarations) - reports.keys()
    unexpected = reports.keys() - set(declarations)
    if missing or unexpected:
        raise ValueError(f"Incomplete axiom audit; missing={sorted(missing)}, unexpected={sorted(unexpected)}")

    failures = {name: report for name, report in reports.items() if report["forbidden_axioms"]}
    return {
        "status": "fail" if failures else "pass",
        "method": "Lean #print axioms on declarations imported through Solution",
        "toolchain": (ROOT / "lean-toolchain").read_text(encoding="utf-8").strip(),
        "permitted_axioms": sorted(STANDARD_AXIOMS),
        "main_theorem": MAIN_THEOREM,
        "challenge_imported": False,
        "declarations": reports,
        "scope_note": "Axiom-dependency audit only; full sandboxed Comparator verification is separate.",
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", help="Emit the structured audit report")
    arguments = parser.parse_args()
    try:
        report = audit()
    except (OSError, ValueError, subprocess.TimeoutExpired) as error:
        if arguments.json:
            print(json.dumps({"status": "error", "error": str(error)}, indent=2))
        else:
            print(f"Proof-status audit failed: {error}", file=sys.stderr)
        return 2
    if arguments.json:
        print(json.dumps(report, indent=2))
    else:
        for name, declaration in report["declarations"].items():
            forbidden = declaration["forbidden_axioms"]
            if forbidden:
                print(f"FAIL {name}: forbidden axioms {', '.join(forbidden)}")
            else:
                print(f"PASS {name}: standard axioms only")
        if report["status"] == "fail":
            print("The proof development is incomplete; the Challenge's deliberate hole is excluded.")
        else:
            print("Axiom dependencies pass; sandboxed Comparator remains the independent proof check.")
    return 1 if report["status"] == "fail" else 0


if __name__ == "__main__":
    sys.exit(main())
